ether = 10**18
gwei = 10**10

ATTACKER = "attacker"
DEAD = "dead"
ZERO = "zero"

MSG_SENDER_ADDR = "msg.sender"
DEAD_ADDR = "0xdead"
ZERO_ADDR = "0x0"

UNISWAP_V2PAIR_CONTRACT_NAME = "UniswapV2Pair"
PANCAKE_V2PAIR_CONTRACT_NAME = "PancakePair"
USDCE_CONTRACT_NAME = "USDCE"
USDT_CONTRACT_NAME = "USDT"
WETH_CONTRACT_NAME = "WETH"
WBNB_CONTRACT_NAME = "WBNB"
BUSD_CONTRACT_NAME = "BUSD"
