project_name: "MUMUG"

# Abstract name of a DeFi contract and its class name.
ctrt_name2cls:
  - ["mu", "Mu"]
  - ["usdce", "USDCE"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]
  - ["mubank", "MuBank"]

# For contract deployment
ctrt_name2deploy:
  - ["mu", "new Mu(totalSupplymu)"]
  - ["usdce", ""]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  - ["mubank", "new MuBank(address(router), address(pair), address(mu))"]

extra_actions:
  - "function swap_mubank_usdce_mu(uint256 sendAmount) internal {
    usdce.approve(address(mubank), type(uint).max);
    mubank.mu_bond(address(usdce), sendAmount);
    }"

extra_deployments: []

extra_statements: []

attack_goal_str: "usdce;1e6"

groundtruth:
  - ["borrow", "mu", "99000e18"]
  - ["swap", "pair", "mu", "usdce", "99000e18"]
  - ["swap", "mubank", "usdce", "mu", "22960e18"]
  - ["payback", "mu", "99297e18"]

roles:
  "usdce":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "mu":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "mubank":
    is_swappair: true
    support_swaps:
      "usdce": ["mu", "usdce"]
  "pair":
    is_swappair: true
    uniswap_order: ["usdce", "mu"]
    support_swaps:
      "mu": ["mu", "usdce"]
      "usdce": ["mu", "usdce"]
    is_oracle: true

pattern: "Price Discrepancy"
